# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
AWS_ACCESS_KEY: "AWS_ACCESS_KEY"
AWS_SECRET_KEY: "vni+AWS_SECRET_KEY"
AWS_BUCKET: "AWS_BUCKET"
AWS_REGION: "us-east-2"
gmail_username: 'fashioNTWRKtesting@gmail.com'
gmail_password: 'test123#'
facebook_client_id: '529985925072978'
facebook_client_secret: 'd76f6eaaa6d11b8a0bd7c1d17849ddae'
google_client_id: '334277817273-j2jeoq27e9lmijpeiqbruseq94i64dh6.apps.googleusercontent.com'
google_client_secret: 'dgdnNbSSYUJnIaYvg7aBWJLf'